# Generated by Django 4.0.5 on 2022-06-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20220602_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['num_order'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии мест'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='num_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='1 - обложка достопримечательности', verbose_name='Порядковый номер'),
        ),
    ]
