# Generated by Django 4.0.5 on 2022-06-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_photo_options_alter_photo_num_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
