# Generated by Django 4.0.5 on 2022-06-10 08:57

from django.db import migrations


def change_null(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        if not place.description_short:
            place.description_short = ''
            place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_description_long'),
    ]

    operations = [
        migrations.RunPython(change_null)
    ]
