# Generated by Django 4.0.5 on 2022-06-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20220610_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['pk'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
